### ISSUE TITLE
setup.sh won't create y base folder by itself

### ISSUE THREAD

**Issue by johanneshoess** [colorchestra/y#1]
`Creating daily directories... `
`mkdir: das Verzeichnis »/home/jo/y/data//today“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
`
because `BASEDIR=~/y` isn't there yet.

Could have done pull request. Didn't do it-tho'.

**Comment by colorchestra** [comment]
The 'y' directory is created by Git when you clone the repo, so that should work. It seems you haven't cloned it to your home directory, but somewhere else? If you want to do that, just edit the `BASEDIR` variable in setup.sh to reflect the location you want y to run from. I'll add that to the README asap.
